import { expect, it } from "vitest";
import { buildSweepReview } from "@/lib/sweep-review";
import type { OHLCBar } from "@/lib/macd";
import { completedDailyBars } from "@/lib/market-bars";

const baseline = (): OHLCBar[] => Array.from({ length: 30 }, (_, i) => ({ time: new Date(Date.UTC(2026, 6, i + 1)).toISOString().slice(0, 10), open: 104, high: 106, low: 102, close: 105, volume: 100 }));
const sweepBars = () => { const bars = baseline(); bars[28] = { ...bars[28], low: 99, high: 103, open: 101, close: 102, volume: 200 }; return bars; };
const sweep = { index: 28, time: "2026-07-29", direction: "bullish" as const, level: { price: 100, type: "low" as const, source: "Swing", startTime: "2026-07-11", startIndex: 10 }, wickExtreme: 99, closePrice: 102, volumeRatio: 2 };
const row = (review: ReturnType<typeof buildSweepReview>, id: string) => review.checks.find(check => check.id === id);

it("compares event-day price, penetration, close strength and median volume separately from latest close", () => { const result = buildSweepReview(sweep, sweepBars()); for (const id of ["wick", "close-back", "penetration", "close-strength", "volume", "latest-side"]) expect(row(result, id)?.status).toBe("met"); expect(row(result, "volume")?.date).toBe(sweep.time); expect(row(result, "availability")?.status).toBe("unavailable"); });
it("does not call the event candle a subsequent hold", () => { expect(row(buildSweepReview(sweep, sweepBars().slice(0, -1)), "latest-side")?.status).toBe("not-applicable"); });
it("uses explicit confirmation dates and supplies follow-up conditions", () => { const event = { ...sweep, level: { ...sweep.level, confirmedIndex: 20, confirmedTime: "2026-07-21" } }; const result = buildSweepReview(event, sweepBars()); expect(row(result, "availability")?.status).toBe("met"); expect(result.summary.join(" ")).toContain("水平確認日 2026-07-21"); expect(result.guidance?.join(" ")).toContain("$100.00"); });
it("accepts session levels whose source bar is also confirmation", () => { const event = { ...sweep, level: { ...sweep.level, source: "PDL", confirmedIndex: 10, confirmedTime: "2026-07-11" } }; expect(row(buildSweepReview(event, sweepBars()), "availability")?.status).toBe("met"); });
it("never claims an event-day confirmation was previously available", () => { const event = { ...sweep, level: { ...sweep.level, confirmedIndex: 28, confirmedTime: sweep.time } }; expect(row(buildSweepReview(event, sweepBars()), "availability")?.status).toBe("not-met"); });
it("keeps the original event when latest close is on the wrong side", () => { const bars = sweepBars(); bars[29] = { ...bars[29], low: 98, high: 101, close: 99 }; const result = buildSweepReview(sweep, bars); expect(row(result, "close-back")?.status).toBe("met"); expect(row(result, "latest-side")?.status).toBe("not-met"); });
it("computes bearish comparisons symmetrically", () => { const bars = sweepBars().map(bar => ({ ...bar, open: 200 - bar.open, high: 200 - bar.low, low: 200 - bar.high, close: 200 - bar.close })); const result = buildSweepReview({ ...sweep, direction: "bearish", level: { ...sweep.level, type: "high" }, wickExtreme: 101, closePrice: 98 }, bars); expect(row(result, "wick")?.status).toBe("met"); expect(row(result, "close-back")?.status).toBe("met"); });
it("treats zero/invalid median volume as unavailable", () => { const bars = sweepBars().map(bar => ({ ...bar, volume: 0 })); bars[28].volume = 200; const result = buildSweepReview(sweep, bars); expect(row(result, "volume")?.status).toBe("unavailable"); expect(JSON.stringify(result)).not.toMatch(/NaN|Infinity/); });
it("distinguishes missing pre-event volume history", () => { const bars = sweepBars().slice(15); const event = { ...sweep, index: 13, level: { ...sweep.level, startIndex: 0, startTime: bars[0].time } }; expect(row(buildSweepReview(event, bars), "volume")?.status).toBe("unavailable"); });
it("rejects mismatched event dates and prices", () => { expect(buildSweepReview({ ...sweep, time: "2026-07-28" }, sweepBars()).checks).toEqual([]); expect(buildSweepReview({ ...sweep, closePrice: 99 }, sweepBars()).checks).toEqual([]); });
it("handles insufficient data without inventing events", () => { expect(buildSweepReview(null, []).summary.join(" ")).toContain("資料不足"); expect(buildSweepReview(null, baseline().slice(0, 2)).summary.join(" ")).toContain("資料不足"); });
it.each([{ low: 99.95, expected: "met" }, { low: 97, expected: "met" }, { low: 96.99, expected: "not-met" }, { low: 100, expected: "not-met" }])("checks penetration boundary at $low", ({ low, expected }) => { const bars = sweepBars().map(bar => ({ ...bar, open: bar.open * 20, high: bar.high * 20, low: bar.low * 20, close: bar.close * 20 })); bars[28].low = low * 20; expect(row(buildSweepReview({ ...sweep, level: { ...sweep.level, price: 2000 }, wickExtreme: low * 20, closePrice: 2040 }, bars), "penetration")?.status).toBe(expected); });
it("rejects equal-level closes and checks actual volume", () => { const bars = sweepBars(); bars[28] = { ...bars[28], close: 100, volume: 50 }; const result = buildSweepReview({ ...sweep, closePrice: 100 }, bars); expect(row(result, "close-back")?.status).toBe("not-met"); expect(row(result, "volume")?.status).toBe("not-met"); });
it("unfinished candles cannot confirm a Sweep event", () => { const data = completedDailyBars(sweepBars().slice(0, -1), "2026-07-29T15:00:00Z"); expect(buildSweepReview(sweep, data).checks).toEqual([]); });
it("distinguishes an empty filtered list from insufficient data", () => { expect(buildSweepReview(null, baseline()).summary.join(" ")).toContain("目前篩選範圍沒有"); });
it("does not draw conclusions across invalid historical price bars", () => { expect(buildSweepReview(sweep, [...sweepBars(), { ...baseline()[0], time: "2026-07-30", high: NaN }]).checks).toEqual([]); });
