"""
Accumulation Tracker Walk-Forward Backtest.

Validates Spring/LPS/SOS trigger signals with proper out-of-sample testing.

Design:
  - Walk-forward: rolling train/test windows
  - Parameter robustness: sweep CONFIRM_THRESHOLD and PROMOTION_STREAK
  - No look-ahead bias: triggers evaluated using only data available at that point
  - Statistical significance: require 50+ trades

Usage:
    python backtest_accumulation.py
    python backtest_accumulation.py --symbols NVDA,AMD,AAPL
    python backtest_accumulation.py --robustness
    python backtest_accumulation.py --days 750
"""

import argparse
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from copy import deepcopy

import numpy as np
import pandas as pd
import yfinance as yf

from config import SYMBOLS, DEFAULT_CFG
from strategies.accumulation.detector import compute_daily_score
from strategies.accumulation.phase_classifier import classify_phase
from strategies.accumulation.entry_triggers import check_triggers


# ─── Configuration ───────────────────────────────────────────────────────────

@dataclass
class BacktestConfig:
    # Walk-forward windows
    train_days: int = 365       # Training window size
    test_days: int = 180        # Test window size
    step_days: int = 90         # Step between windows

    # Trade parameters
    max_hold_spring: int = 30
    max_hold_lps: int = 20
    max_hold_sos: int = 15
    slippage_pct: float = 0.05

    # Accumulation parameters (to be swept in robustness test)
    confirm_threshold: int = 11
    promotion_streak: int = 2
    entry_threshold: int = 5    # Min score to enter tracking

    # Filters
    min_phase: str = "any"      # "any" or "C", "D" to filter triggers
    tier_filter: str = "any"    # "any", "watch", "confirmed"


@dataclass
class Trade:
    symbol: str
    trigger_type: str       # "SPRING", "LPS", "SOS_BREAKOUT"
    phase: str
    tier: str
    decay_score: float
    entry_price: float
    stop_loss: float
    target: float
    entry_date: str
    exit_date: str = ""
    exit_price: float = 0.0
    pnl_pct: float = 0.0
    pnl_r: float = 0.0
    hold_days: int = 0
    result: str = ""        # "WIN", "LOSS", "TIMEOUT"


# ─── Core Engine ─────────────────────────────────────────────────────────────

class AccumulationBacktester:
    def __init__(self, config: BacktestConfig):
        self.config = config

    def download_data(self, symbols: list[str], total_days: int = 1000) -> dict:
        """Download historical data for all symbols."""
        print(f"  Downloading {len(symbols)} symbols ({total_days} days)...")
        data = {}
        period = f"{total_days}d"

        # Download SPY for relative strength
        spy_df = yf.download("SPY", period=period, progress=False)
        if isinstance(spy_df.columns, pd.MultiIndex):
            spy_df.columns = spy_df.columns.get_level_values(0)
        data["__SPY__"] = spy_df

        for sym in symbols:
            try:
                df = yf.download(sym, period=period, progress=False)
                if isinstance(df.columns, pd.MultiIndex):
                    df.columns = df.columns.get_level_values(0)
                if df is not None and len(df) >= 120:
                    data[sym] = df
            except Exception:
                pass

        print(f"  Downloaded {len(data) - 1}/{len(symbols)} symbols")
        return data

    def simulate_tracking(self, df: pd.DataFrame, spy_df: pd.DataFrame,
                          start_idx: int, end_idx: int, cfg: BacktestConfig) -> list[Trade]:
        """
        Simulate accumulation tracking over a date range.
        Returns list of trades generated by triggers.
        """
        trades = []

        if len(df) < end_idx or len(spy_df) < end_idx:
            return trades

        # State for this symbol
        tracking = False
        decay_score = 0.0
        promote_streak = 0
        tier = "watch"
        phase = "UNKNOWN"

        for i in range(start_idx, end_idx):
            # Need at least 60 bars of history
            if i < 60:
                continue

            # Get data up to current bar (no look-ahead)
            df_slice = df.iloc[:i + 1]
            spy_slice = spy_df.iloc[:i + 1] if len(spy_df) > i else spy_df

            try:
                # Compute daily score
                result = compute_daily_score(df_slice.tail(130), spy_slice.tail(130))
                if isinstance(result, dict):
                    raw_score = result.get("raw_score", 0)
                    support_primary = result.get("support_primary", 0)
                    support_dynamic = result.get("support_dynamic", 0)
                    resistance = result.get("resistance", 0)
                else:
                    continue

                # Entry/exit tracking
                if not tracking:
                    if raw_score >= cfg.entry_threshold:
                        tracking = True
                        decay_score = raw_score
                    continue

                # Update decay score
                decay_rate = 0.85
                decay_score = max(raw_score, decay_score * decay_rate)

                # Exit tracking if score too low
                if decay_score < 3:
                    tracking = False
                    decay_score = 0
                    promote_streak = 0
                    tier = "watch"
                    continue

                # Promotion logic
                if decay_score >= cfg.confirm_threshold:
                    promote_streak += 1
                else:
                    promote_streak = 0

                if promote_streak >= cfg.promotion_streak:
                    tier = "confirmed"

                # Phase classification
                try:
                    phase_result = classify_phase(
                        df_slice.tail(130), support_primary, support_dynamic, resistance
                    )
                    if isinstance(phase_result, dict):
                        phase = phase_result.get("phase", "UNKNOWN")
                    elif isinstance(phase_result, str):
                        phase = phase_result
                except Exception:
                    phase = "UNKNOWN"

                # Apply filters
                if cfg.tier_filter != "any" and tier != cfg.tier_filter:
                    continue
                if cfg.min_phase != "any" and phase not in cfg.min_phase.split(","):
                    continue

                # Check triggers
                try:
                    triggers = check_triggers(
                        df_slice.tail(60), phase,
                        support_primary, support_dynamic, resistance
                    )
                except Exception:
                    triggers = []

                if not triggers:
                    continue

                # Process each trigger
                for trig in triggers:
                    trig_type = trig.get("type", "") if isinstance(trig, dict) else str(trig)

                    # Determine max hold
                    if "SPRING" in trig_type:
                        max_hold = cfg.max_hold_spring
                    elif "LPS" in trig_type:
                        max_hold = cfg.max_hold_lps
                    else:
                        max_hold = cfg.max_hold_sos

                    entry_price = float(df_slice["Close"].iloc[-1])
                    sl = support_primary if support_primary > 0 else entry_price * 0.95
                    tp = resistance if resistance > 0 else entry_price * 1.10

                    # Skip if R:R < 1.0
                    risk = entry_price - sl
                    reward = tp - entry_price
                    if risk <= 0 or reward / risk < 1.0:
                        continue

                    # Apply slippage
                    entry_price *= (1 + cfg.slippage_pct / 100)

                    # Simulate trade forward
                    trade = self._simulate_trade(
                        df, i, entry_price, sl, tp, max_hold, trig_type, phase, tier, decay_score
                    )
                    if trade:
                        trades.append(trade)

            except Exception:
                continue

        return trades

    def _simulate_trade(self, df: pd.DataFrame, entry_idx: int,
                        entry: float, sl: float, tp: float,
                        max_hold: int, trig_type: str,
                        phase: str, tier: str, decay_score: float) -> Trade | None:
        """Simulate a single trade from entry_idx forward."""
        if entry_idx + 1 >= len(df):
            return None

        trade = Trade(
            symbol=df.index[entry_idx].strftime("%Y-%m-%d") if hasattr(df.index[entry_idx], 'strftime') else "",
            trigger_type=trig_type,
            phase=phase,
            tier=tier,
            decay_score=decay_score,
            entry_price=entry,
            stop_loss=sl,
            target=tp,
            entry_date=str(df.index[entry_idx].date()) if hasattr(df.index[entry_idx], 'date') else "",
        )
        trade.symbol = ""  # Will be set by caller

        risk = entry - sl
        if risk <= 0:
            return None

        for j in range(1, min(max_hold + 1, len(df) - entry_idx)):
            bar = df.iloc[entry_idx + j]
            low = float(bar["Low"])
            high = float(bar["High"])
            close = float(bar["Close"])

            # Check stop loss (hit intrabar)
            if low <= sl:
                trade.exit_price = sl
                trade.pnl_pct = (sl - entry) / entry * 100
                trade.pnl_r = -1.0
                trade.result = "LOSS"
                trade.hold_days = j
                trade.exit_date = str(df.index[entry_idx + j].date()) if hasattr(df.index[entry_idx + j], 'date') else ""
                return trade

            # Check target (hit intrabar)
            if high >= tp:
                trade.exit_price = tp
                trade.pnl_pct = (tp - entry) / entry * 100
                trade.pnl_r = (tp - entry) / risk
                trade.result = "WIN"
                trade.hold_days = j
                trade.exit_date = str(df.index[entry_idx + j].date()) if hasattr(df.index[entry_idx + j], 'date') else ""
                return trade

        # Timeout: exit at close of last day
        last_idx = min(entry_idx + max_hold, len(df) - 1)
        exit_price = float(df.iloc[last_idx]["Close"])
        trade.exit_price = exit_price
        trade.pnl_pct = (exit_price - entry) / entry * 100
        trade.pnl_r = (exit_price - entry) / risk
        trade.result = "WIN" if exit_price > entry else "LOSS"
        trade.hold_days = last_idx - entry_idx
        trade.exit_date = str(df.index[last_idx].date()) if hasattr(df.index[last_idx], 'date') else ""
        return trade

    def walk_forward(self, data: dict, symbols: list[str], cfg: BacktestConfig) -> dict:
        """
        Run walk-forward backtest across multiple windows.
        Returns aggregated results.
        """
        spy_df = data.get("__SPY__")
        if spy_df is None or len(spy_df) < 200:
            return {"trades": [], "windows": []}

        # Determine total date range
        max_len = max(len(data[sym]) for sym in symbols if sym in data)
        total_bars = max_len

        # Generate windows
        windows = []
        train_size = cfg.train_days
        test_size = cfg.test_days
        step = cfg.step_days

        start = 0
        while start + train_size + test_size <= total_bars:
            windows.append({
                "train_start": start,
                "train_end": start + train_size,
                "test_start": start + train_size,
                "test_end": start + train_size + test_size,
            })
            start += step

        if not windows:
            # Fallback: single window
            split = int(total_bars * 0.7)
            windows = [{
                "train_start": 0,
                "train_end": split,
                "test_start": split,
                "test_end": total_bars,
            }]

        print(f"  Walk-forward: {len(windows)} windows")

        all_trades = []
        window_results = []

        for wi, w in enumerate(windows):
            window_trades = []

            for sym in symbols:
                if sym not in data or sym == "__SPY__":
                    continue
                df = data[sym]
                if len(df) < w["test_end"]:
                    continue

                # Only use test period for trade evaluation
                # (train period is for "building up" the tracker state)
                trades = self.simulate_tracking(
                    df, spy_df,
                    start_idx=w["train_start"],  # Build state during train
                    end_idx=w["test_end"],
                    cfg=cfg,
                )

                # Only count trades that ENTERED during test period
                test_start_date = df.index[w["test_start"]] if w["test_start"] < len(df) else None
                for t in trades:
                    t.symbol = sym
                    if test_start_date and t.entry_date >= str(test_start_date.date()):
                        window_trades.append(t)

            # Window metrics
            if window_trades:
                wr = sum(1 for t in window_trades if t.result == "WIN") / len(window_trades) * 100
                exp = np.mean([t.pnl_r for t in window_trades])
                window_results.append({
                    "window": wi + 1,
                    "trades": len(window_trades),
                    "win_rate": wr,
                    "expectancy": exp,
                })
            else:
                window_results.append({
                    "window": wi + 1,
                    "trades": 0,
                    "win_rate": 0,
                    "expectancy": 0,
                })

            all_trades.extend(window_trades)

        return {"trades": all_trades, "windows": window_results}

    def robustness_sweep(self, data: dict, symbols: list[str]) -> list[dict]:
        """
        Sweep CONFIRM_THRESHOLD and PROMOTION_STREAK to find robust parameters.
        Returns list of {threshold, streak, sharpe, win_rate, trades, expectancy}.
        """
        print("\n  Running parameter robustness sweep...")
        results = []

        thresholds = [8, 9, 10, 11, 12, 13, 14]
        streaks = [1, 2, 3, 4]

        total = len(thresholds) * len(streaks)
        done = 0

        for thresh in thresholds:
            for streak in streaks:
                done += 1
                cfg = deepcopy(self.config)
                cfg.confirm_threshold = thresh
                cfg.promotion_streak = streak

                result = self.walk_forward(data, symbols, cfg)
                trades = result["trades"]

                if len(trades) >= 10:
                    pnls = [t.pnl_r for t in trades]
                    wr = sum(1 for t in trades if t.result == "WIN") / len(trades) * 100
                    exp = np.mean(pnls)
                    sharpe = exp / np.std(pnls) if np.std(pnls) > 0 else 0
                else:
                    wr = 0
                    exp = 0
                    sharpe = 0

                results.append({
                    "threshold": thresh,
                    "streak": streak,
                    "trades": len(trades),
                    "win_rate": round(wr, 1),
                    "expectancy": round(exp, 3),
                    "sharpe": round(sharpe, 3),
                })

                print(f"    [{done}/{total}] T={thresh} S={streak}: "
                      f"{len(trades)} trades, WR={wr:.1f}%, Exp={exp:+.2f}R, Sharpe={sharpe:.2f}")

        return results


# ─── Reporting ───────────────────────────────────────────────────────────────

def print_report(result: dict, config: BacktestConfig):
    """Print comprehensive backtest report."""
    trades = result["trades"]
    windows = result["windows"]

    print(f"\n{'='*65}")
    print(f"  ACCUMULATION TRACKER — WALK-FORWARD BACKTEST REPORT")
    print(f"{'='*65}")

    if not trades:
        print("  ❌ No trades generated.")
        return

    total = len(trades)
    wins = [t for t in trades if t.result == "WIN"]
    losses = [t for t in trades if t.result == "LOSS"]
    win_rate = len(wins) / total * 100

    pnls = [t.pnl_r for t in trades]
    expectancy = np.mean(pnls)
    total_r = sum(pnls)
    sharpe = expectancy / np.std(pnls) if np.std(pnls) > 0 else 0
    avg_hold = np.mean([t.hold_days for t in trades])

    # Max drawdown in R
    cumulative = np.cumsum(pnls)
    peak = np.maximum.accumulate(cumulative)
    dd = cumulative - peak
    max_dd = abs(min(dd)) if len(dd) > 0 else 0

    print(f"\n  Config: CONFIRM_THRESHOLD={config.confirm_threshold}, "
          f"PROMOTION_STREAK={config.promotion_streak}")
    print(f"  Windows: {len(windows)} | Total Trades: {total}")
    print(f"\n  {'─'*60}")
    print(f"  Win Rate:    {win_rate:.1f}%")
    print(f"  Expectancy:  {expectancy:+.3f}R")
    print(f"  Sharpe:      {sharpe:.2f}")
    print(f"  Total R:     {total_r:+.1f}R")
    print(f"  Max DD:      {max_dd:.1f}R")
    print(f"  Avg Hold:    {avg_hold:.0f} days")

    if wins:
        print(f"  Avg Win:     +{np.mean([t.pnl_r for t in wins]):.2f}R")
    if losses:
        print(f"  Avg Loss:    {np.mean([t.pnl_r for t in losses]):.2f}R")

    # By trigger type
    print(f"\n  {'─'*60}")
    print(f"  {'Trigger':<20} {'Trades':>7} {'WR':>7} {'Exp':>8} {'Avg Hold':>9}")
    print(f"  {'─'*20} {'─'*7} {'─'*7} {'─'*8} {'─'*9}")

    for trig in ["SPRING", "LPS", "SOS_BREAKOUT"]:
        tt = [t for t in trades if trig in t.trigger_type]
        if tt:
            t_wr = sum(1 for t in tt if t.result == "WIN") / len(tt) * 100
            t_exp = np.mean([t.pnl_r for t in tt])
            t_hold = np.mean([t.hold_days for t in tt])
            print(f"  {trig:<20} {len(tt):>7} {t_wr:>6.1f}% {t_exp:>+7.3f}R {t_hold:>8.0f}d")

    # By tier
    print(f"\n  {'─'*60}")
    print(f"  {'Tier':<20} {'Trades':>7} {'WR':>7} {'Exp':>8}")
    print(f"  {'─'*20} {'─'*7} {'─'*7} {'─'*8}")

    for tier_name in ["watch", "confirmed"]:
        tt = [t for t in trades if t.tier == tier_name]
        if tt:
            t_wr = sum(1 for t in tt if t.result == "WIN") / len(tt) * 100
            t_exp = np.mean([t.pnl_r for t in tt])
            print(f"  {tier_name:<20} {len(tt):>7} {t_wr:>6.1f}% {t_exp:>+7.3f}R")

    # Window consistency
    print(f"\n  {'─'*60}")
    print(f"  Walk-Forward Window Consistency:")
    positive_windows = sum(1 for w in windows if w["expectancy"] > 0)
    print(f"  Positive windows: {positive_windows}/{len(windows)}")
    for w in windows:
        emoji = "✅" if w["expectancy"] > 0 else "❌"
        print(f"    {emoji} Window {w['window']}: {w['trades']} trades, "
              f"WR={w['win_rate']:.1f}%, Exp={w['expectancy']:+.3f}R")

    print(f"\n{'='*65}")

    # Verdict
    print(f"\n  📊 VERDICT:")
    issues = []
    if total < 50:
        issues.append(f"交易次數不足 ({total} < 50)")
    if sharpe < 1.0:
        issues.append(f"Sharpe 偏低 ({sharpe:.2f} < 1.0)")
    if win_rate < 50:
        issues.append(f"勝率偏低 ({win_rate:.1f}% < 50%)")
    if positive_windows < len(windows) * 0.6:
        issues.append(f"Window 一致性差 ({positive_windows}/{len(windows)})")

    if not issues:
        print("  ✅ 策略通過驗證 — 各指標健康")
    else:
        print("  ⚠️  需要注意：")
        for issue in issues:
            print(f"     • {issue}")

    print()


def print_robustness(results: list[dict]):
    """Print robustness sweep as a heatmap-style table."""
    print(f"\n{'='*65}")
    print(f"  PARAMETER ROBUSTNESS — Sharpe by (Threshold, Streak)")
    print(f"{'='*65}\n")

    thresholds = sorted(set(r["threshold"] for r in results))
    streaks = sorted(set(r["streak"] for r in results))

    # Header
    header = "Thresh\\Streak"
    print(f"  {header:<14}", end="")
    for s in streaks:
        print(f"{'S=' + str(s):>10}", end="")
    print()
    print(f"  {'─'*14}", end="")
    for _ in streaks:
        print(f"{'─'*10}", end="")
    print()

    # Rows
    best_sharpe = max(r["sharpe"] for r in results)

    for t in thresholds:
        print(f"  T={t:<11}", end="")
        for s in streaks:
            r = next((x for x in results if x["threshold"] == t and x["streak"] == s), None)
            if r:
                sharpe = r["sharpe"]
                # Mark best with star
                marker = " ★" if sharpe == best_sharpe and sharpe > 0 else ""
                print(f"{sharpe:>8.2f}{marker}", end="")
            else:
                print(f"{'N/A':>10}", end="")
        print()

    print(f"\n  {'─'*60}")

    # Find plateau (robust region)
    good_results = [r for r in results if r["sharpe"] > best_sharpe * 0.7 and r["trades"] >= 20]
    if good_results:
        print(f"\n  🏔️  Robust region (Sharpe > {best_sharpe * 0.7:.2f}):")
        for r in sorted(good_results, key=lambda x: -x["sharpe"])[:5]:
            print(f"    T={r['threshold']}, S={r['streak']}: "
                  f"Sharpe={r['sharpe']:.2f}, WR={r['win_rate']}%, "
                  f"{r['trades']} trades")

    print(f"\n{'='*65}\n")


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Accumulation Tracker Walk-Forward Backtest")
    parser.add_argument("--symbols", type=str, default="",
                        help="Comma-separated symbols (default: all)")
    parser.add_argument("--days", type=int, default=900,
                        help="Total history days to download (default: 900)")
    parser.add_argument("--robustness", action="store_true",
                        help="Run parameter robustness sweep")
    parser.add_argument("--threshold", type=int, default=11,
                        help="CONFIRM_THRESHOLD (default: 11)")
    parser.add_argument("--streak", type=int, default=2,
                        help="PROMOTION_STREAK (default: 2)")
    args = parser.parse_args()

    symbols = args.symbols.split(",") if args.symbols else SYMBOLS[:30]  # Default: top 30

    config = BacktestConfig(
        confirm_threshold=args.threshold,
        promotion_streak=args.streak,
    )

    backtester = AccumulationBacktester(config)

    print(f"\n{'━'*65}")
    print(f"  Accumulation Tracker — Walk-Forward Backtest")
    print(f"  Symbols: {len(symbols)} | History: {args.days} days")
    print(f"  CONFIRM_THRESHOLD={config.confirm_threshold} | PROMOTION_STREAK={config.promotion_streak}")
    print(f"{'━'*65}")

    # Download data
    data = backtester.download_data(symbols, total_days=args.days)

    if args.robustness:
        # Parameter sweep
        results = backtester.robustness_sweep(data, symbols)
        print_robustness(results)
    else:
        # Single run
        result = backtester.walk_forward(data, symbols, config)
        print_report(result, config)


if __name__ == "__main__":
    main()
